### ISSUE TITLE
differentiable lbfgs 

### ISSUE THREAD

**Issue by wangleiphy** [facebookresearch/higher#2]
Hi, thanks for the wonderful code! 
Would it be possible to support a differentiable lbfgs optimizer? That will be very useful for cases without stochasticity.

**Comment by egrefen** [comment]
Thank you @wangleiphy. It should be possible, subject to the update step being mathematically differentiable. The way LBFGS is implemented in `torch.optim` is a little different than the other optimizers, so it would it is non-trivial. We would love to get around to this, but it is not high-priority. We welcome pull requests, and give details in https://github.com/facebookresearch/higher#adding-your-own-optimizers about how to add support for "new" optimizers.

**Comment by egrefen** [comment]
Having looked into the implementation of LBFGS and our own needs + spare time, we realistically won't have time to look into this ourselves. Following the instructions linked to above, we hope someone will be interested in supplying an implementation of LBFGS in the form of a pull request in the future.
