### ISSUE TITLE
Memory leak in loop with higher.innerloop_ctx!

### ISSUE THREAD

**Issue by nooralahzadeh** [facebookresearch/higher#37]
I saw this problem was solved however, I still have it:

I am using the last version of higher 0.1.5, however still have a problem with memory leak:
```ruby
with higher.innerloop_ctx(model, inner_opt, copy_initial_weights=False) as (fast_model, diffopt):
          for step, batch in enumerate(epoch_iterator):
                    report_memory()
                    print("-------------")
                    fast_model.train()
                    outputs = fast_model(batch)
                    loss = outputs[0]  
                    diffopt.step(loss)
```

> memory (MB) | allocated: 678.73095703125 | max allocated: 678.73095703125 | cached: 734.0 | max cached: 734.0
> memory (MB) | allocated: 1357.4619140625 | max allocated: 2036.19287109375 | cached: 2158.0 | max cached: 2158.0
> memory (MB) | allocated: 12340.314453125 | max allocated: 13059.771484375 | cached: 13208.0 | max cached: 13208.0
> memory (MB) | allocated: 23322.634765625 | max allocated: 24041.8564453125 | cached: 24190.0 | max cached: 24190.0

**Comment by egrefen** [comment]
Evidently it is not fixed or I have reintroduced a reference cycle. I will look into it over the next week or so. In the meantime, I recommend running the inner loop on CPU (use the `device` keyword) to mitigate the problem.

**Comment by renesax14** [comment]
how do we install a version of higher without this issue?

**Comment by nooralahzadeh** [comment]
There is no any version that mitigate this issue as I understood. It is on progress to solve !

**Comment by egrefen** [comment]
@nooralahzadeh This is normal behaviour. While you are in the context (or generally speaking, using the patched model), the history of activations and parameters of `fast_model` is preserved in memory. This is, in fact, exactly what the `higher` library is designed to do, as preserving these in memory with an implicit backwards graph allows you to backpropagate through the unrolled optimization loop. 

I am closing this issue, but you are welcome to re-open and comment if this explanation does not answer your question, or this behaviour is not what you were expecting for some reason (please explain) or you were trying to do something different and need assistance.

**Comment by tathagatv** [comment]
@egrefen I'm facing this issue with the `higher` library when I am using the [higher.path.make_functional](https://higher.readthedocs.io/en/latest/patch.html#higher.patch.make_functional) function to make a forward pass through an LSTM model. 
How should I explicitly delete the backwards graph when I'm done with the inner and outer loop steps? As of now, the GPU consumption keeps increasing as more batches are processed.
