### ISSUE TITLE
_cudnn_rnn_backward is not implemented

### ISSUE THREAD

**Issue by nooralahzadeh** [facebookresearch/higher#4]
Hi, 
I have a following error in my code, however I am using torch 1.3 .
RuntimeError: derivative for _cudnn_rnn_backward is not implemented
I know that it is pytorch related error. I am wondering in which version of pytorch it has been resolved!

Solved by using following code :
`with torch.backends.cudnn.flags(enabled=False): `

**Comment by egrefen** [comment]
Thanks for closing the task. This is a CUDNN issue, as noted here: https://github.com/facebookresearch/higher#knownpossible-issues

I see you found the solution.

If you're interested in tracking the cudnn-related issue itself, it's here: https://github.com/pytorch/pytorch/issues/5261

**Comment by tengerye** [comment]
@nooralahzadeh Hi, I encountered similar problems, too. May I ask where did you put `with torch.backends.cudnn.flags(enabled=False):` please?

**Comment by nooralahzadeh** [comment]
Hi @tengerye , following https://github.com/facebookresearch/higher#knownpossible-issues, I put that before meta-leaning method, where you call your meta-learing method, for example:
`with torch.backends.cudnn.flags(enabled=False):
               meta_params= meta_learn(meta_model,....)`

**Comment by egrefen** [comment]
@tengerye Let me know if you have any issues...

I should probably look into whether or not it's possible to automatigically use this when using CUDA and the higher context manager...

**Comment by tengerye** [comment]
@nooralahzadeh @egrefen Thank you so much for your kind reply. I am not working on meta-learning actually, but something else. I tried the following way, but it fails to work:
```
    jacobian = torch.autograd.grad(
        y, x, grad_outputs=ws, create_graph=True)

    with torch.backends.cudnn.flags(enabled=False):
        Jv = torch.autograd.grad(
            torch.cat([var.flatten() for var in jacobian]),
            ws,
            grad_outputs=torch.cat(v).flatten(), retain_graph=True)
```
May I ask for some suggestions please?

**Comment by nooralahzadeh** [comment]
Did you try it before the jacobian"
`with torch.backends.cudnn.flags(enabled=False):
jacobian = torch.autograd.grad(
    y, x, grad_outputs=ws, create_graph=True)
    Jv = torch.autograd.grad(
        torch.cat([var.flatten() for var in jacobian]),
        ws,
        grad_outputs=torch.cat(v).flatten(), retain_graph=True)`

**Comment by tengerye** [comment]
@nooralahzadeh Yes, I did.

**Comment by tengerye** [comment]
Hi, I figured it out. We should place `torch.backends.cudnn.flags(enabled=False):` before the creation of model and the **context** should last after the higher derivatives.
