### ISSUE TITLE
Multiple GPU training support

### ISSUE THREAD

**Issue by bruceshuyu** [facebookresearch/higher#40]
I'm wondering is multi-GPU training fully supported in the current version. When I add net = torch.nn.DataParallel(net). It seems to report an tensor key error.

**Comment by egrefen** [comment]
We looked into this as part of #24 and at this stage, support for `higher` in DataParallel would be quite complicated and necessitate changes to core pytorch. Your best bet is to raise an issue on the pytorch repo linking back to this issue and #24, with details of the crash. We don't have the bandwidth (or technical knowledge) to make these changes ourselves.
