### ISSUE TITLE
Why are you not using torchmeta?

### ISSUE THREAD

**Issue by renesax14** [facebookresearch/higher#66]
https://tristandeleu.github.io/pytorch-meta/api_reference/datasets/

**Comment by egrefen** [comment]
TorchMeta provides some excellent data loaders (great work @tristandeleu and team!), and a meta-module API that makes it easy to implement new modules in a meta-learning compatible way. AFAIK, it does introduce some restrictions, and also doesn't support existing/saved modules, whereas `higher`'s  monkey-patching logic does. Furthermore it only supports SGD as an optimizer, whereas we cover (nearly) all optimizers from `torch.optim`. For these reasons, my recommendation is to use torchmeta's data loaders in conjunction with `higher`, as [shown in this example](https://github.com/tristandeleu/pytorch-meta/tree/master/examples/maml-higher). Both libraries work quite well together in this sense, allowing users to write compact and natural meta-learning code without writing much non-standard pytorch, and unleashing the power of existing model implementations and other libraries.
