### ISSUE TITLE
Discrepancy between Adam and DifferentiableAdam

### ISSUE THREAD

**Issue by neitzal** [facebookresearch/higher#71]
I noticed a slight discrepancy between the implementations of `torch.optim.Adam` and `higher.optim.DifferentiableAdam`: in the former, we add epsilon after dividing by `sqrt(bias_correction_2)`; in the latter, we add epsilon before the division.

The relevant lines are: 
https://github.com/pytorch/pytorch/blob/master/torch/optim/adam.py#L109
https://github.com/facebookresearch/higher/blob/master/higher/optim.py#L360

This leads to different behavior of the two optimizers, especially in early iterations. 
Was this intended?

**Comment by egrefen** [comment]
Hello @neitzal. It seems this discrepancy was introduced in https://github.com/pytorch/pytorch/commit/fed5ca192c98619947cca2fb9491ac9624b787d2 last August. It's easily fixable. Would you like to submit a fix via pull request? If not, I can probably fix this in the next week or so when I find half an hour.

**Comment by neitzal** [comment]
Thanks! I just made a pull request: #72
