### ISSUE TITLE
How to train a model inside an innerloop context without higher order gradients?

### ISSUE THREAD

**Issue by ferreirafabio** [facebookresearch/higher#81]
I would like to train a **model B** with simple first-order gradients inside the `innerloop_ctx` of **model A** optimized with higher order gradients. In particular, after training **B**, I want to do inference on it to use the **model B** output in a loss function to train **A** with higher-order gradients. If I do this, I end up with the error: 

> RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.

Here's an example:

```python
global_target = ... a tensor of scalar values
with higher.innerloop_ctx(learner, optim, override={
                'lr': [learner_lr],
                'momentum': [learner_momentum]
                }) as (flearner, diffopt):

    model_A_outputs = []
    model_A_targets = []
    for step in range(5):
        model_A_output, model_A_target = model_A(model_A_input[step], id_to_one_hot(model_A_input_target[step], target_classes).squeeze(1))

        model_A_outputs.append(model_A_output)
        model_A_targets.append(model_A_target)

        learner_output = flearner(model_A_output)
        loss = self.get_loss(output=learner_output, target=model_A_target)
        diffopt.step(loss)

    model_B = train_model_B(data=model_A_outputs, 
                           targets=model_A_targets,
                           ) # --> this calls the loss.backward() function on model_B training and throws the above error 
    #sample some data from a dataset and store in "data"
    model_A_output = flearner(data)
    model_B_output = model_B(data).detach()

    loss = F.margin_ranking_loss(model_A_output, model_B_output, target=global_target)
    loss.backward()
optimizer_outer.step()
```

If I pass `retain_graph=True` to the loss.backward() function inside `train_model_B()` I can get around this error. However, I don't know if this is what I want. I think there must be a way of denoting that the call of `train_model_B()` does not need higher order gradients and can be trained "normally" with 1st order gradient optimization. I tried wrapping `model_B` with `model_B = higher.patch.monkeypatch(model_B, track_higher_grads =False)` but that did not help either.

**Comment by egrefen** [comment]
Hello. Can you point to the line where this error would originate in your example and/or provide a full stack trace, please?

**Comment by egrefen** [comment]
Ah I see you've pointed to the line in a comment. Can you please provide a stack trace?

**Comment by egrefen** [comment]
Also since the error happens within `train_model_B` I would need to see what the code for that function is.

**Comment by ferreirafabio** [comment]
@egrefen thanks for the quick reply. Fortunately, I was able to solve the problem and the cause of it was that I had forgotten to detach model_A_outputs :). Sorry for this inconvenience. Keep up the great work!
