### ISSUE TITLE
MAML++ implementation?

### ISSUE THREAD

**Issue by brando90** [facebookresearch/higher#84]
I noticed MAML is really unreliable. Is there a MAML++ implementation?

crossposted: https://discuss.pytorch.org/t/maml-implementation-in-pytorch/100409

**Comment by egrefen** [comment]
@bamos has one. We should really look into integrating that into example folder...

**Comment by bamos** [comment]
Hi @brando90, I just added you to our private repo with this implementation. We'll look more into posting this publicly

**Comment by bamos** [comment]
Hi, these are available at https://github.com/bamos/HowToTrainYourMAMLPytorch

**Comment by egrefen** [comment]
Thanks Brandon! Accepted PR #86 so I'm closing this issue.
