### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_parameters'

### ISSUE THREAD

**Issue by zhaozj89** [facebookresearch/higher#89]
Hi, thanks for this work.

When I used `higher` for a cutomized network inheritated from `torch.nn.Module`, it reported the following error when it excutated  at `higher.innerloop_ctx(self.online_net, inner_opt, copy_initial_weights=False) as (fnet, diffopt):`

`AttributeError: 'NoneType' object has no attribute '_parameters'`

<img width="1414" alt="Screenshot 2020-11-12 at 8 51 30 PM" src="https://user-images.githubusercontent.com/34164876/98942398-e4a6fa80-2528-11eb-9a7b-f2e03801063a.png">

I can print the network with `.parameters`. What could be the problem? Thanks.

**Comment by zhaozj89** [comment]
My problem. Close it.

**Comment by egrefen** [comment]
I love it when problems solve themselves 😄
