### ISSUE TITLE
Is higher compatibale with distributed data parallel DDP ?

### ISSUE THREAD

**Issue by brando90** [facebookresearch/higher#98]
like this one: https://pytorch.org/tutorials/intermediate/ddp_tutorial.html

**Comment by brando90** [comment]
related: https://github.com/tristandeleu/pytorch-meta/issues/100

**Comment by brando90** [comment]
related: https://github.com/facebookresearch/higher/issues/99

**Comment by brando90** [comment]
crosspsoted: https://discuss.pytorch.org/t/is-the-higher-level-library-for-meta-learning-compatible-with-pytorchs-distributed-libraries/112753

**Comment by egrefen** [comment]
I'm afraid not. See answer to #99.

**Comment by brando90** [comment]
related: https://github.com/tristandeleu/pytorch-meta/issues/116

**Comment by brando90** [comment]
@albanD is there progress on this? (sorry for the direct tag)

**Comment by albanD** [comment]
I don't know of any change in DDP towards this recently. But I'm not aware of all that happens there.
cc @mrshenli anything that I missed?

**Comment by brando90** [comment]
> I don't know of any change in DDP towards this recently. But I'm not aware of all that happens there. cc @mrshenli anything that I missed?

Hi!

has there been any progress on this? @mrshenli
